### ISSUE TITLE
network diagrams(ports,interfaces,etc)

### ISSUE THREAD

**Issue by dpiscia** [RD-Connect/Infrastracture#1]

**Comment by miguelbernadi** [comment]
Created small diagram on https://www.gliffy.com/go/documentManager Invitation only for now, looking for a way to export the diagram. Invited dpiscia to check and modify it.

**Comment by miguelbernadi** [comment]
Initial version exported!

![rdconnect_overview](https://cloud.githubusercontent.com/assets/731219/7939767/ff4100f0-094c-11e5-8db9-66db8f17e635.png)

**Comment by miguelbernadi** [comment]
Second version of diagram, more complete and differentiating Management from Operation flows.
![rdconnect_overview 1](https://cloud.githubusercontent.com/assets/731219/7941261/52e9fc08-0956-11e5-8580-4a5fe56af239.png)

**Comment by dpiscia** [comment]
Rd-connect proxy,do we have one?

**Comment by dpiscia** [comment]
close it now, open new #28 , #27
