### ISSUE TITLE
jenkins env

### ISSUE THREAD

**Issue by dpiscia** [RD-Connect/Infrastracture#3]

**Comment by dpiscia** [comment]
Can we install it in the genomics development machine for the moment?

**Comment by miguelbernadi** [comment]
The genomics development machine is the pilot to test using a controlled
installation method. Once the test is deemed correctly finished we may
install the jenkins, pending Anibal's approval.

**Comment by dpiscia** [comment]
How the test is going? Can we install jenkins on dev machine?

**Comment by miguelbernadi** [comment]
Jenkins installed and running on 10.3.231.66:8080

**Comment by dpiscia** [comment]
very good!!!

**Comment by dpiscia** [comment]
DOne
